### ISSUE TITLE
You're awesome

### ISSUE THREAD

**Issue by mightyiam** [noopkat/avrgirl#1]
@noopkat you're awesome. [Great inspiring talk just went up](https://youtu.be/VxxTkhSTJbA).

**Comment by noopkat** [comment]
@mightyiam this just made my day, thank you so much :grin:

**Comment by k45514n** [comment]
This issue is verified replicatable under varying, nearly all conditions <3

**Comment by noopkat** [comment]
@nodebotanist :heart:

**Comment by ichpuchtli** [comment]
Can confirm.
